from playwright.sync_api import Page, expect

def test_bai_tap_buoi_4(page:Page):
    page.goto("https://hrm.anhtester.com/")
    page.get_by_placeholder("Your Username").fill("admin_example")
    page.get_by_placeholder("Enter Password").fill("123456")
    page.get_by_role("button", name="Login").click()
    expect(page.get_by_role("link", name="Logout")).to_be_visible()
    page.get_by_role("link", name="Manage Clients").click()
    page.get_by_role("link", name="Add New").click()
    page.get_by_placeholder("First Name").fill("GMO")
    page.get_by_placeholder("Last Name").fill("Testing")
    page.get_by_placeholder("Password").fill("123456") 
    page.get_by_placeholder("Contact Number").fill("0123456789")
    dropdown = page.locator("//span[@role = 'combobox']")
    dropdown.locator("//span[@role = 'textbox']").click()
    dropdown.get_by_text("Male").click()
    page.get_by_placeholder("Email").fill("gmo@gmail.com")
    page.get_by_placeholder("Username").fill("Ka Li Test")
    page.get_by_role("button", name="Choose File").set_input_files("C:\\Users\\GMO\\OneDrive\\Desktop\\playwright-python-032026\\Ka Li\\BTBuoi4\\demo_example.jpg")
    page.get_by_role("button", name="Save").click()
    expect(page.locator("#xin_table")).to_contain_text("GMO Testing")
